name: integrity ci

on:
  - push
  - pull_request

jobs:
  integrity:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-node@v3
        name: install Node.js (20.11.1)
        with:
          node-version: 20.11.1

      - uses: pnpm/action-setup@v3
        name: install pnpm
        with:
          version: 8.15.5
          run_install: false

      - name: get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install

      - name: build and run tests
        run: pnpm test



