name: publish-npm-package

on:
    release:
        types:
            - edited
            - released

jobs:
    publish-npm-package:
        runs-on: ubuntu-latest

        steps:
            # execute source code checkout
            -   uses: actions/checkout@v3
                name: checkout

            # install nodejs version 20.11.1
            -   uses: actions/setup-node@v4
                name: install Node.js (20.11.1)
                with:
                    node-version: 20.11.1
                    registry-url: 'https://registry.npmjs.org'

            # install PNPM version 8.15.5
            -   uses: pnpm/action-setup@v3
                name: install pnpm
                with:
                    version: 8.15.5
                    run_install: false

            # get the pnpm store path
            -   name: get pnpm store directory
                shell: bash
                run: |
                    echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            # create cache keys
            -   uses: actions/cache@v3
                name: setup pnpm cache
                with:
                    path: ${{ env.STORE_PATH }}
                    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                    restore-keys: |
                        ${{ runner.os }}-pnpm-store-

            # get the release tag to use as package version
            -   uses: jannemattila/get-version-from-tag@v3
                id: get_version
                name: get tag version to use as package version

            # apply new version
            -   shell: bash
                name: apply new version
                run: |
                    npm version ${{ steps.get_version.outputs.version }}

            # install dependencies in production context
            -   name: install dependencies
                run: pnpm install --frozen-lockfile

            # build dist to use as package
            -   name: build dist
                run: pnpm build

            # publish NPM package
            -   shell: bash
                name: publish NPM package
                run: |
                    cd dist
                    npm publish
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
